CREATE TABLE specializations (
    specialization_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,

    CONSTRAINT pk_specializations
        PRIMARY KEY (specialization_id),

    CONSTRAINT uq_specializations_name
        UNIQUE (name)
);

CREATE TABLE doctors (
    doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    specialization_id NUMBER NOT NULL,

    CONSTRAINT pk_doctors
        PRIMARY KEY (doctor_id),

    CONSTRAINT fk_doctors_specialization
        FOREIGN KEY (specialization_id)
        REFERENCES specializations(specialization_id)
);

CREATE TABLE patients (
    patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    birth_date DATE NOT NULL,
    phone VARCHAR2(20),
    email VARCHAR2(100),

    CONSTRAINT pk_patients
        PRIMARY KEY (patient_id),

    CONSTRAINT uq_patients_email
        UNIQUE (email)
);

CREATE TABLE appointments (
    appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id NUMBER NOT NULL,
    doctor_id NUMBER NOT NULL,
    appointment_date TIMESTAMP NOT NULL,
    status VARCHAR2(20) DEFAULT 'SCHEDULED' NOT NULL,
    notes VARCHAR2(500),

    CONSTRAINT pk_appointments
        PRIMARY KEY (appointment_id),

    CONSTRAINT fk_appointments_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients(patient_id),

    CONSTRAINT fk_appointments_doctor
        FOREIGN KEY (doctor_id)
        REFERENCES doctors(doctor_id),

    CONSTRAINT chk_appointments_status
        CHECK (status IN ('SCHEDULED', 'COMPLETED', 'CANCELLED'))
);
