CREATE TABLE specializations (
    specialization_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,

    CONSTRAINT pk_specializations
        PRIMARY KEY (specialization_id),

    CONSTRAINT uq_specializations_name
        UNIQUE (name)
);

CREATE TABLE doctors (
    doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    specialization_id NUMBER NOT NULL,

    CONSTRAINT pk_doctors
        PRIMARY KEY (doctor_id),

    CONSTRAINT fk_doctors_specialization
        FOREIGN KEY (specialization_id)
        REFERENCES specializations(specialization_id)
);

CREATE TABLE patients (
    patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    birth_date DATE NOT NULL,
    phone VARCHAR2(20),
    email VARCHAR2(100),

    CONSTRAINT pk_patients
        PRIMARY KEY (patient_id),

    CONSTRAINT uq_patients_email
        UNIQUE (email)
);

CREATE TABLE appointments (
    appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id NUMBER NOT NULL,
    doctor_id NUMBER NOT NULL,
    appointment_date TIMESTAMP NOT NULL,
    status VARCHAR2(20) DEFAULT 'SCHEDULED' NOT NULL,
    notes VARCHAR2(500),

    CONSTRAINT pk_appointments
        PRIMARY KEY (appointment_id),

    CONSTRAINT fk_appointments_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients(patient_id),

    CONSTRAINT fk_appointments_doctor
        FOREIGN KEY (doctor_id)
        REFERENCES doctors(doctor_id),

    CONSTRAINT chk_appointments_status
        CHECK (status IN ('SCHEDULED', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE medical_records (
    record_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id NUMBER NOT NULL,
    doctor_id NUMBER NOT NULL,
    diagnosis VARCHAR2(500) NOT NULL,
    treatment VARCHAR2(1000),
    record_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_medical_records
        PRIMARY KEY (record_id),

    CONSTRAINT fk_medical_records_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients(patient_id),

    CONSTRAINT fk_medical_records_doctor
        FOREIGN KEY (doctor_id)
        REFERENCES doctors(doctor_id)
);

CREATE TABLE medications (
    medication_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    price NUMBER(10, 2) NOT NULL,

    CONSTRAINT pk_medications
        PRIMARY KEY (medication_id),

    CONSTRAINT uq_medications_name
        UNIQUE (name),

    CONSTRAINT chk_medications_price
        CHECK (price >= 0)
);

CREATE TABLE prescriptions (
    prescription_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id NUMBER NOT NULL,
    doctor_id NUMBER NOT NULL,
    medication_id NUMBER NOT NULL,
    dosage VARCHAR2(100) NOT NULL,
    frequency VARCHAR2(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,

    CONSTRAINT pk_prescriptions
        PRIMARY KEY (prescription_id),

    CONSTRAINT fk_prescriptions_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients(patient_id),

    CONSTRAINT fk_prescriptions_doctor
        FOREIGN KEY (doctor_id)
        REFERENCES doctors(doctor_id),

    CONSTRAINT fk_prescriptions_medication
        FOREIGN KEY (medication_id)
        REFERENCES medications(medication_id),

    CONSTRAINT chk_prescriptions_dates
        CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE payments (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    appointment_id NUMBER NOT NULL,
    amount NUMBER(10, 2) NOT NULL,
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    payment_method VARCHAR2(20) NOT NULL,
    status VARCHAR2(20) DEFAULT 'PAID' NOT NULL,

    CONSTRAINT pk_payments
        PRIMARY KEY (payment_id),

    CONSTRAINT fk_payments_appointment
        FOREIGN KEY (appointment_id)
        REFERENCES appointments(appointment_id),

    CONSTRAINT chk_payments_amount
        CHECK (amount > 0),

    CONSTRAINT chk_payments_method
        CHECK (payment_method IN ('CASH', 'CARD', 'TRANSFER')),

    CONSTRAINT chk_payments_status
        CHECK (status IN ('PAID', 'REFUNDED', 'PENDING'))
);
